using OpenQA.Selenium;

namespace AutomationPractice.PageObjects;

public class Facade
{
    private CartPage cartPage;
    private DressesPage dressesPage;
    private HomePage homePage;
    private LoginPage loginPage;
    private ProductPage productPage;
    private SignUpPage signUpPage;
    private UserHomePage userHomePage;
    private WishListsPage wishListsPage;

    public Facade()
    {
        cartPage = Page.CartPage;
        dressesPage = Page.DressesPage;
        homePage = Page.HomePage;
        loginPage = Page.Login;
        productPage = Page.ProductPage;
        signUpPage = Page.SignUp;
        userHomePage = Page.UserHomePage;
        wishListsPage = Page.WishLists;
    }

    public bool LoginInIntoAnAccount(string username, string password)
    {
        loginPage = loginPage.LoadPage();

        if (!loginPage.IsPageLoaded()) { return false; }

        userHomePage = loginPage.FillLogInDetails(username, password);
        return userHomePage.IsPageLoaded();
    }

    public bool CreateAnAccount(string firstName, string lastName, string email, string password,
        string address, string city, string state, string zipCode, string country, string mobile_phone, string alias)
    {
        loginPage = loginPage.LoadPage();

        if (!loginPage.IsPageLoaded()) { return false; }

        signUpPage = loginPage.SubmitEmailForm(email);
        if (!signUpPage.IsPageLoaded())
        {
            return false;
        }

        userHomePage = signUpPage.FillRegistrationForm(firstName, lastName, email, password,
        address, city, state, zipCode, country, mobile_phone, alias);
        return userHomePage.IsPageLoaded();
    }

    public bool AddToAutoCreatedWishlist(string username, string password)
    {
        loginPage = loginPage.LoadPage();

        if (!loginPage.IsPageLoaded()) { return false; }

        userHomePage = loginPage.FillLogInDetails(username, password);

        if (!userHomePage.IsPageLoaded())
        {
            return false;
        }

        wishListsPage = userHomePage.ClickWishlist();

        if (!wishListsPage.IsPageLoaded() || wishListsPage.DoesAutoGeneratedWishListExist())
        {
            return false;
        }

        productPage = wishListsPage.ClickProduct();

        if (!productPage.IsPageLoaded()) { return false; }

        productPage = productPage.AddToWishList();

        wishListsPage = productPage.GoToUserHomePage().ClickWishlist();

        return wishListsPage.CheckProductAddedToAutoWishList();
    }

    public bool AddToCustomWishlist(string username, string password, string cartName)
    {
        loginPage = loginPage.LoadPage();

        if (!loginPage.IsPageLoaded()) { return false; }

        userHomePage = loginPage.FillLogInDetails(username, password);

        if (!userHomePage.IsPageLoaded())
        {
            return false;
        }

        wishListsPage = userHomePage.ClickWishlist();

        if (!wishListsPage.IsPageLoaded())
        {
            return false;
        }

        wishListsPage = wishListsPage.CreateMyWishList(cartName);

        if (!wishListsPage.DoesCustomWishlistWasCreated(cartName))
        {
            return false;
        }

        productPage = wishListsPage.ClickProduct();

        if (!productPage.IsPageLoaded()) { return false; }

        productPage = productPage.AddToWishList();

        wishListsPage = productPage.GoToUserHomePage().ClickWishlist();

        return wishListsPage.CheckProductAddedToCustomWishList(cartName); 
    }

    public bool AbleToAddThreeItemsToTheCart(string username, string password)
    {
        loginPage = loginPage.LoadPage();

        if (!loginPage.IsPageLoaded()) { return false; }

        userHomePage = loginPage.FillLogInDetails(username, password);

        if (!userHomePage.IsPageLoaded())
        {
            return false;
        }

        dressesPage = userHomePage.ClickDressesOption();
        if (!dressesPage.IsPageLoaded()) { return false; }

        dressesPage = dressesPage.AddThreeDressesToTheCart();
        cartPage = dressesPage.GoToCart();

        if (cartPage.CountProductsInTheCart() != 3 || cartPage.GetCartTotal() != 107.97)
        {
            return false;
        }

        return true;
    }
}
